[package]
name = "timeline_database"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["connect", "rustls-tls-webpki-roots"] }
futures-util = "0.3"
prost = "0.14.4"
rusqlite = { version = "0.40", features = ["bundled"] }
uuid = { version = "1.24.0", features = ["v7", "fast-rng"] }

[build-dependencies]
prost-build = "0.14.4"
